http://numba.pydata.org/numba-doc/0.31.0/user/jit.html

In [1]:
from timeit import timeit
from numba import jit
@jit 
def f(x,y):
    return x+y

def fp(x,y):
    return x+y


In [2]:
%timeit f(1,2)
%timeit fp(1,2)

1 loop, best of 3: 0 ns per loop
The slowest run took 34.02 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 56.5 ns per loop


In [3]:
f(1j,2)

(2+1j)

In [4]:
from numba import jit, int32
@jit(int32(int32,int32))
def f(x,y):
    return x+y

In [5]:
f(1,2)

3

In [6]:
 f(2**31, 2**31 + 1)

1

### Calling and inlining other functions
Numba-compiled functions can call other compiled functions. The function calls may even be inlined in the native code, depending on optimizer heuristics. For example:

In [7]:
@jit
def square(x):
    return x**2
@jit
def hypot(x,y):
    return math.sqrt(square(x)+square(y))

#### nopython

In [8]:
@jit(nopython=True)
def f(x,y):
    return x+y

In [9]:
@jit(nogil=True)
def f(x, y):
    return x + y

In [10]:
@jit(cache=True)
def f(x, y):
    return x + y

In [11]:
from numba import vectorize, float64,int64,float32,int32

@vectorize([float64(float64, float64)])
def f(x, y):
    return x + y
@vectorize([int32(int32, int32),
            int64(int64, int64),
            float32(float32, float32),
            float64(float64, float64)])
def f(x, y):
    return x + y

In [12]:
import numpy as np
a = np.arange(6)
f(a, a)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
a = np.linspace(0, 1, 6)
f(a, a)

array([ 0. ,  0.4,  0.8,  1.2,  1.6,  2. ])

In [14]:
from numba import guvectorize
@guvectorize([(int64[:], int64[:], int64[:])], '(n),()->(n)')
def g(x, y, res):
    for i in range(x.shape[0]):
        res[i] = x[i] + y[0]

In [15]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
g(a,2)

array([[2, 3, 4],
       [5, 6, 7]])

In [17]:
g(a,10)

array([[10, 11, 12],
       [13, 14, 15]])