[Sparse Matrix and its representations](https://www.geeksforgeeks.org/sparse-matrix-representation/)

### Method 1: Using Arrays:

2D array is used to represent a sparse matrix in which there are three rows named as 

- Row: Index of row, where non-zero element is located
- Column: Index of column, where non-zero element is located
- Value: Value of the non zero element located at index – (row,column)


In [6]:
# Python program for Sparse Matrix Representation
# using arrays
 
# assume a sparse matrix of order 4*5
# let assume another matrix compactMatrix
# now store the value,row,column of arr1 in sparse matrix compactMatrix
 
sparseMatrix = [[0,0,3,0,4],
                [0,0,5,7,0],
                [0,0,0,0,0],
                [0,2,6,0,0]]
 
# initialize size as 0
size = 0
 
for i in range(4):
    for j in range(5):
        if (sparseMatrix[i][j] != 0):
            size += 1
 
# number of columns in compactMatrix(size) should
# be equal to number of non-zero elements in sparseMatrix
rows, cols = (3, size)
compactMatrix = [[0 for i in range(cols)] for j in range(rows)]
 
k = 0
for i in range(4):
    for j in range(5):
        if (sparseMatrix[i][j] != 0):
            compactMatrix[0][k] = i
            compactMatrix[1][k] = j
            compactMatrix[2][k] = sparseMatrix[i][j]
            k += 1
 
for i in compactMatrix:
    print(i)
 
# This code is contributed by MRINALWALIA

[0, 0, 1, 1, 3, 3]
[2, 4, 2, 3, 1, 2]
[3, 4, 5, 7, 2, 6]


In [7]:
import numpy as np 
sparseMatrix = [[0,0,3,0,4],
                [0,0,5,7,0],
                [0,0,0,0,0],
                [0,2,6,0,0]]

def to_ijv(A):
    size=np.count_nonzero(A)
    rows, cols = np.where(A)
    # compactMatrix = np.zeros((3, size), dtype=dtype)
    compactMatrix = np.zeros((size, 3))
    for i in range(size):
        row, col = rows[i], cols[i]
        compactMatrix[i][0] = row
        compactMatrix[i][1] = col
        compactMatrix[i][2] = A[row][col]
    
    return compactMatrix

 
compactMatrix = to_ijv(sparseMatrix)
fmt = '%d', '%d', '%25.16f'
np.savetxt("A.txt", compactMatrix, fmt=fmt)

In [8]:
import numpy as np 
from scipy.sparse import coo_matrix

def to_ijv(A):

    A_coo = coo_matrix(A)
    size =A_coo.nnz
    A_coo = np.hstack((A_coo.row.reshape(size,1),
                       A_coo.col.reshape(size,1),
                       A_coo.data.reshape(size,1)
                      ))  
    return A_coo


sparseMatrix = [[0,0,3,0,4],
                [0,0,5,7,0],
                [0,0,0,0,0],
                [0,2,6,0,0]]

compactMatrix = to_ijv(sparseMatrix)
print(compactMatrix.shape)
fmt = '%d', '%d', '%25.16f'
np.savetxt("A.txt", compactMatrix, fmt=fmt)

(6, 3)


### Method 2: Using Linked Lists
In linked list, each node has four fields. These four fields are defined as: 

- Row: Index of row, where non-zero element is located
- Column: Index of column, where non-zero element is located
- Value: Value of the non zero element located at index – (row,column)
Next node: Address of the next node

In [9]:
# Python Program for Representation of
# Sparse Matrix into Linked List

# Node Class to represent Linked List Node
class Node:

    # Making the slots for storing row,
    # column, value, and address
    __slots__ = "row", "col", "data", "next"

    # Constructor to initialize the values
    def __init__(self, row=0, col=0, data=0, next=None):

        self.row = row
        self.col = col
        self.data = data
        self.next = next


# Class to convert Sparse Matrix
# into Linked List
class Sparse:

    # Initialize Class Variables
    def __init__(self):
        self.head = None
        self.temp = None
        self.size = 0

    # Function which returns the size
    # of the Linked List
    def __len__(self):
        return self.size

    # Check the Linked List is
    # Empty or not
    def isempty(self):
        return self.size == 0

    # Responsible function to create
    # Linked List from Sparse Matrix
    def create_new_node(self, row, col, data):

        # Creating New Node
        newNode = Node(row, col, data, None)

        # Check whether the List is
        # empty or not
        if self.isempty():
            self.head = newNode
        else:
            self.temp.next = newNode
        self.temp = newNode

        # Incrementing the size
        self.size += 1

    # Function display the contents of
    # Linked List
    def PrintList(self):
        temp = r = s = self.head
        print("row_position:", end=" ")
        while temp != None:
            print(temp.row, end=" ")
            temp = temp.next
        print()
        print("column_postion:", end=" ")
        while r != None:
            print(r.col, end=" ")
            r = r.next
        print()
        print("Value:", end=" ")
        while s != None:
            print(s.data, end=" ")
            s = s.next
        print()

# Driver Code
if __name__ == "__main__":

    # Creating Object
    s = Sparse()

    # Assuming 4x5 Sparse Matrix
    sparseMatric = [[0, 0, 3, 0, 4],
                    [0, 0, 5, 7, 0],
                    [0, 0, 0, 0, 0],
                    [0, 2, 6, 0, 0]]
    for i in range(4):
        for j in range(5):

            # Creating Linked List by only those
            # elements which are non-zero
            if sparseMatric[i][j] != 0:
                s.create_new_node(i, j, sparseMatric[i][j])

    # Printing the Linked List Representation
    # of the sparse matrix
    s.PrintList()

    # This code is contributed by Naveen Rathore


row_position: 0 0 1 1 3 3 
column_postion: 2 4 2 3 1 2 
Value: 3 4 5 7 2 6 


In [10]:
from scipy.sparse import coo_matrix
A = [[0, 0, 3, 0, 4],
    [0, 0, 5, 7, 0],
    [0, 0, 0, 0, 0],
    [0, 2, 6, 0, 0]]
A_coo = coo_matrix(A)
print(A_coo.row)
print(type(A_coo.row))
print(A_coo.col)
print(A_coo.data)

[0 0 1 1 3 3]
<class 'numpy.ndarray'>
[2 4 2 3 1 2]
[3 4 5 7 2 6]
